version: '3'

services:
  spritpreise:
    image: spritpreise:1.0.0
    container_name: spritpreise
    restart: always
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "3005:80"
    env_file:
      - .env

  db:
    image: webhippie/mongodb
    restart: always
    volumes:
      - db:/var/lib/mongodb
      - db-backup:/var/lib/backup

volumes:
  db:
  db-backup:
