version: '3'

services:
  spritpreise:
    image: spritpreise:1.0.0
    container_name: spritpreise
    restart: always
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "3005:80"
    environment:
      - SERVER_PORT=80
      - API_KEY=
      - DB_URL=mongodb://db:27017/spritpreise
      - WEBHOOK_HOST=
      - TELEGRAM_TOKEN=
      - UPDATE_CYCLE=15
      - SEARCH_RADIUS=10

  db:
    image: webhippie/mongodb
    restart: always
    volumes:
      - db:/var/lib/mongodb
      - db-backup:/var/lib/backup

volumes:
  db:
  db-backup:
