version: '3'

services:
  spritpreise:
    image: spritpreise:1.0.0
    container_name: spritpreise
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "3005:80"
    environment:
      - SERVER_PORT=80
      - API_KEY=
      - DB_URL=mongodb://db:27017/spritpreise
      - API_BASE_PATH=/api
      - TELEGRAM_TOKEN=

  db:
    image: mongo:latest
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
