[build]
  command = "export API_URL=https://spritpreise-ihk.com/.netlify/functions/ && cd ./frontend && npm install && npm run build && cd ../server && npm install && npm run build:serverless"
  functions = "server/dist/serverless"