[build]
  command = "export API_URL=https://spritpreise-ihk.com/.netlify/functions/ && cd /frontend && npm run build && cd ../server && npm run build:serverless"
  functions = "server/dist/serverless"